// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5fM2ZVi9yv7cAF8MH_V6Y3S7_jjk4nE',
    appId: '1:352191489715:web:82e881e54944d1f76cb2c6',
    messagingSenderId: '352191489715',
    projectId: 'teste-1fd7c',
    authDomain: 'teste-1fd7c.firebaseapp.com',
    storageBucket: 'teste-1fd7c.appspot.com',
    measurementId: 'G-56ZR2WJ2EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB87tyKck0FpF5eVhh3YcNaThXTZpGL0Ks',
    appId: '1:352191489715:android:8faa04ae2e3ad65c6cb2c6',
    messagingSenderId: '352191489715',
    projectId: 'teste-1fd7c',
    storageBucket: 'teste-1fd7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqKRvvs0oylcXwhS7u8vEXz3SofRsG_zI',
    appId: '1:352191489715:ios:b7239f7883cfa8976cb2c6',
    messagingSenderId: '352191489715',
    projectId: 'teste-1fd7c',
    storageBucket: 'teste-1fd7c.appspot.com',
    iosBundleId: 'com.juliadomingues.flutterproject.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqKRvvs0oylcXwhS7u8vEXz3SofRsG_zI',
    appId: '1:352191489715:ios:f5306c9703cc26396cb2c6',
    messagingSenderId: '352191489715',
    projectId: 'teste-1fd7c',
    storageBucket: 'teste-1fd7c.appspot.com',
    iosBundleId: 'com.juliadomingues.flutterproject.flutterproject.RunnerTests',
  );
}
